name: Sync From Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch From Release Repository'
        required: true

jobs:
  contents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync Full Branches
        run: |
          git fetch --all
          git checkout branch
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make wget curl cloc
      - name: Change Commit
        id: commit
        run: |
          git checkout -b ${{ github.event.inputs.branch }}
          sed -i 's/_BRANCH_/${{ github.event.inputs.branch }}/g' Dockerfile
          git config user.name 'HansBug'
          git config user.email 'hansbug@buaa.edu.cn'
          git add -A
          git diff-index --quiet HEAD || git commit -a -m "dev(hansbug): auto sync $(date -R) from release ${{ github.event.inputs.branch }}"
          git push -f --set-upstream origin ${{ github.event.inputs.branch }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          event-type: data-refreshed
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "branch": "${{ github.event.inputs.branch }}"
              }
            }

